spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JTS_DB?serverTimezone=Asia/Seoul
    username: pys_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 없으면 만들고 있으면 그대로 사용
    show-sql: true # mysql debug mode, 실제 쿼리가 로그로 보임
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        format_sql: true # sql 로그를 포매팅해서 보여줌
  logging:
    level:
      org.hibernate.type: trace # bind 쿼리의 내용까지 출력. ? 부분이 실제 값으로 표현됨
server:
  port: 8080

